language: python
python:
  - "3.6.6"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - flake8 website/ pages/
  - pytest pages --conv=pages
#  - python manage.py test -v 2
#  - py.test --cov=pytocli tests/
#  - python -m doctest README.md
# after_success:
#  - coveralls