language: python
python: 3.8-dev

services:
  postgresql
addons:
  postgresql: '9.5'
# command to install dependencies
install:
  - cp contrib/env-sample-travis-ci .env
  - pip install -r requirements-dev.txt
#before_script:
  - psql -c "CREATE DATABASE travis_ci_db;" -U postgres
  - python manage.py migrate --noinput
# command to run tests
script:
  - flake8 .
  - pytest --cov='.'
#after_success:
#  - codecov