# Generated by Django 2.0.7 on 2018-07-20 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotolito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=10)),
                ('largura', models.CharField(max_length=10)),
                ('cores', models.CharField(max_length=10)),
                ('finalidade', models.CharField(choices=[('OFFSET', 'Impressão Off Set'), ('VERNIZ', 'Reserva Verniz'), ('SILK', 'Silk Scren')], default='OFFSET', max_length=20)),
                ('camada', models.CharField(choices=[('LEGIVEL', 'Legível'), ('ILEGIVEL', 'Ilegível')], default='LEGIVEL', max_length=20)),
                ('lineatura', models.CharField(choices=[(40, '40'), (60, '60'), (80, '80'), (100, '100'), (120, '120'), (150, '150'), (175, '175'), (200, '200')], default=175, max_length=10)),
                ('arquivo', models.FileField(upload_to="documents/<class 'django.contrib.auth.models.User'>/%Y/%m/%d/")),
                ('recomendacoes', models.TextField()),
                ('aprovacao', models.CharField(choices=[('NÃO', 'Excluir processo de aprovação'), ('SIM', 'Quero receber um PDF final para aprovação')], default='NÃO', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fotolitos',
            },
        ),
    ]
