# Generated by Django 2.0.7 on 2018-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotolito',
            name='lineatura',
            field=models.CharField(choices=[('40', '40'), ('60', '60'), ('80', '80'), ('100', '100'), ('120', '120'), ('150', '150'), ('175', '175'), ('200', '200')], default=175, max_length=10),
        ),
    ]
