# Generated by Django 2.0.7 on 2018-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20180720_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotolito',
            name='arquivo',
            field=models.FileField(upload_to='documents/<django.db.models.query_utils.DeferredAttribute object at 0x10331bcf8>/%Y/%m/%d/'),
        ),
    ]
